INSERT INTO USERS (USERNAME, PASSWORD, ROLE, ENABLED)
VALUES ('user',
'{noop}user',
'ROLE_USER', 1);

INSERT INTO USERS (USERNAME, PASSWORD, ROLE, ENABLED)
VALUES ('admin',
'{noop}admin',
'ROLE_ADMIN', 1);